#ifndef MODBUSPOLLER_GLOBAL_H
#define MODBUSPOLLER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MODBUSPOLLER_LIBRARY)
#  define MODBUSPOLLERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MODBUSPOLLERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MODBUSPOLLER_GLOBAL_H
